#Application Configuration
spring:
  application:
    name: ${WESHOPIFY_GATEWAY_APP_NAME:weshopify-gateway-server}

#Server Config
server:
  port: ${WESHOPIFY_GATEWAY_PORT:80}

#Profiles Config
  profile: ${WESHOPIFY_GATEWAY_PROFILE:dev}

---
spring:
  config:
    activate:
      on-profile: dev
#Gateway Metrices enabled
  cloud:
    gateway:
      metrics:
        enabled: true
# Discovery Service enabled
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #Routes Config
      routes:
        - id: 01-weshopify-authn-svc
          predicates:
            - Path=/weshopify/auth/**
          uri: lb://WESHOPIFY-AUTHN-SVC
          filters:
            - RewritePath=/weshopify/auth/?(?<segment>.*),/$\{segment}
            - name: CircuitBreaker
              args:
                name: weshopify-authn-circuit-breaker
                fallbackUri: forward:/api/gateway/authn/failed

#Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

#Eureka Config
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${WESHOPIFY_REGISTRY_PROTOCOL:http}://${WESHOPIFY_REGISTRY_HOST:localhost}:${WESHOPIFY_REGISTRY_PORT:8761}/eureka
  instance:
    hostname: ${WESHOPIFY_REGISTRY_HOST:localhost}
