#Service Name

spring:
  application:
    name: ${APP_NAME:WESHOPIFY-USER_MGMT-SVC}

#Profile

  profiles:
    active: ${DB_PROFILE:dev}

#Datasource

# Server Port
server:
  port: 8061


---
#Dev Profile
spring:
  datasource:
    driver-class-name: ${DB_DRIVER_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DB_PROTOCOL:jdbc}:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:weshopify_users}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}

  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

---
#QA Profile
spring:
  datasource:
    driver-class-name: ${DB_DRIVER_NAME:org.h2.Driver}
    url: ${DB_PROTOCOL:jdbc}:${DB_TYPE:h2}:${DB_HOST:mem}:${DB_SCHEMA:weshopify_users}
    username: ${DB_USER:sa}
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: true
      path: /h2console
  config:
    activate:
      on-profile: qa
---
