#Service Name

spring:
  application:
    name: ${USER_APP_NAME:WESHOPIFY-USER_MGMT-SVC}


#sendgrid api api key = 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

#Profile

  profiles:
    active: ${USER_APP_PROFILE:dev}

#Datasource

# Server Port
server:
  port: ${USER_APP_PORT:8061}
# context-path
  servlet:
    context-path: /dev


---
#Dev Profile
spring:
  datasource:
    driver-class-name: ${USER_DB_DRIVER_NAME:com.mysql.cj.jdbc.Driver}
    url: ${USER_DB_PROTOCOL:jdbc}:${USER_DB_TYPE:mysql}://${USER_DB_HOST:localhost}:${USER_DB_PORT:3306}/${USER_DB_SCHEMA:weshopify_users}
    username: ${USER_DB_USER:root}
    password: ${USER_DB_PASS:root}

  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

#Eureka Config
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUERKA_URL:http://localhost:8761/eureka}

---
#QA Profile
spring:
  datasource:
    driver-class-name: ${USER_DB_DRIVER_NAME:org.h2.Driver}
    url: ${USER_DB_PROTOCOL:jdbc}:${USER_DB_TYPE:h2}:${USER_DB_HOST:mem}:${USER_DB_SCHEMA:weshopify_users}
    username: ${USER_DB_USER:sa}
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2console
  config:
    activate:
      on-profile: qa

#Eureka Config
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUERKA_URL:http://localhost:8761/eureka}
---
