
#Server Config
server:
  port: ${APP_PORT:8064}
  servlet:
    context-path: /dev


#Application Config
spring:
  application:
    name: ${APP_NAME:WESHOPIFY-AUTHN-SVC}
  profiles:
    active: ${APP_PROFILE:dev}

---
#Profile Config
spring:
  config:
    activate:
      on-profile: dev

#LOG Config
logging:
  file:
    name: ${LOG_FILE_PATH:D:/logs/codebrains/logs}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{5} [%file:%line] - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} [%file:%line] - %msg%n'
  level:
    root: ERROR
    org:
      springframework: ERROR
      cb: DEBUG
    hibernate: ERROR

#Eureka Config
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUERKA_URL:http://localhost:8761/eureka}

---
#Profile Config
spring:
  config:
    activate:
      on-profile: qa

#LOG Config
logging:
  file:
    name: ${LOG_FILE_PATH:D:/logs/codebrains/logs}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{5} [%file:%line] - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} [%file:%line] - %msg%n'
  level:
    root: ERROR
    org:
      springframework: ERROR
      cb: DEBUG
    hibernate: ERROR

#Eureka Config
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUERKA_URL:http://localhost:8761/eureka}

---
spring:
  config:
    activate:
      on-profile: prod


#LOG Config
logging:
  file:
    name: ${LOG_FILE_PATH:D:/logs/codebrains/logs}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{5} [%file:%line] - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} [%file:%line] - %msg%n'
  level:
    root: ERROR
    org:
      springframework: ERROR
      cb: DEBUG
    hibernate: ERROR

#Eureka Config
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUERKA_URL:http://localhost:8761/eureka}
